### ISSUE TITLE
只能创建空文件夹

### ISSUE THREAD

**Issue by lxy-Jason** [1084350607/type-challenge-helper#1]
![image](https://user-images.githubusercontent.com/94227696/179391494-b262a0a7-899f-4663-a00a-3a8615414cb9.png)

**Comment by JiuRanYa** [comment]
Maybe:
```
npm uninstall -g type-challenge-helper github-files-fetcher
```
then

```
npm install -g type-challenge-helper github-files-fetcher
```

**Comment by 1084350607** [comment]
你可以在终端运行fetcher，确保依赖安装成功
```
fetcher
```

**Comment by JiuRanYa** [comment]
你可以在终端尝试运行以下命令：
```
fetcher --url=https://github.com/type-challenges/type-challenges/blob/main/questions/00191-medium-append-argument/template.ts
```
如果成功fetch到文件说明没有问题，如果没有文件那是因为网络问题，github访问速度低

**Comment by lxy-Jason** [comment]
确定了是网络原因
![image](https://user-images.githubusercontent.com/94227696/179391812-d2a457d9-92b6-47d1-a1df-afc7f8c9d4b0.png)
不过我可以打开通过浏览器打开github,也用了梯子.我该怎么解决这个问题呢

**Comment by JiuRanYa** [comment]
Github上有非常好用的开源软件：https://github.com/freefq/free

**Comment by JiuRanYa** [comment]
也许这个更好用一些：https://github.com/dotnetcore/FastGithub

我之前用过的

**Comment by lxy-Jason** [comment]
我有梯子.用了梯子能通过浏览器打开github,但是fetcher显示:
      No internet, try:

      - Checking the network cables, modem, and router
      - Reconnecting to Wi-Fi

**Comment by JiuRanYa** [comment]
本地会有host，工具是从github fetch文件，走的是github的开源API，能打开github也不代表可以访问github的API，我用的是公司的VPN，一切正常～，也许你可以换一个VPN试试

**Comment by lxy-Jason** [comment]
好的,我再试试
